#ifndef __H_EXTEND_MEDIA_END_ENTITY_TYPE_H__
#define __H_EXTEND_MEDIA_END_ENTITY_TYPE_H__

enum EXTEND_MEDIA_END_ENTITY_TYPE{
	EXTEND_MEDIA_END_ENTITY_BEGIN = MEDIA_END_ENTITY_TYPE_END +1,
};

#endif

